### PR TITLE
Create Reconstruction Insights

### PR DESCRIPTION
**Pull request by ps2270**

### CODE REVIEW

**Comment by ps2270** [comment]
Naomi, I used an online HTML converter, but I think I did not succeed in editing it properly.

**Comment by njr2128** [comment]
The major problem was that the file did not have any sort of extension - we need it to be a markdown file, so I added ".md" to the name which converted automatically through github. I also changed the filename to be machine readable (no spaces) and lowercase (just to match our other files)

**Comment by njr2128** [comment]
part of #32

**Comment by njr2128** [comment]
> Naomi, I used an online HTML converter, but I think I did not succeed in editing it properly. Oh, now I have a better idea about how to edit it, but how do I go back to do that...I'm still working on it.

@ps2270, you can now go in and edit the file in markdown like any of the other files in our repo: https://github.com/cu-mkp/edition-webpages/blob/master/docs/reconstruction-insights.md

**Pull request merged**
